default_config:

homeassistant:
  elevation: 117
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

tts:
  - platform: google_translate

alert: !include_dir_merge_named alerts/

automation bedroom: !include bedroom/automations.yaml
automation general_shopping: !include general/shopping_automations.yaml
automation home_server: !include general/home_server_automations.yaml
automation zigbee2mqtt: !include zigbee2mqtt/automations.yaml

binary_sensor general: !include general/binary_sensors.yaml 
binary_sensor bathroom: !include bathroom/binary_sensors.yaml
binary_sensor office: !include office/binary_sensors.yaml
binary_sensor toilet: !include toilet/binary_sensors.yaml

group: !include_dir_merge_named groups/

influxdb:
  host: !secret influx_host
  database: home_assistant
  username: !secret influx_user
  password: !secret influx_password
  exclude:
    entities:
      - sensor.active_dhcp_leases
      - sensor.known_devices
      - sensor.wifi_connections_sensor
http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_certificate_key_path
  ip_ban_enabled: true
  login_attempts_threshold: 5

homekit:
  - filter:
      include_entities:
      # living room
        - sensor.living_room_sensor_actor_1_temperature
        - sensor.living_room_sensor_actor_1_humidity
        - binary_sensor.living_room_sensor_actor_1_motion_detected
        - light.living_room_center_1
        - light.living_room_center_2
        - light.living_room_center_3
        - light.living_room_center_4
        - light.living_room_center_5
        - light.hue_iris_light
        - light.living_room_sensor_actor_1_closet_rgb_lights
        - light.living_room_standing_light
        - light.living_room_sensor_actor_2_light_strings
        - input_boolean.living_room_light_automation_is_enabled
      # bedroom
        - sensor.bedroom_sensor_humidity
        - sensor.bedroom_sensor_temperature
        - binary_sensor.bedroom_sensor_motion_detected
        - light.bedroom_ceiling_1
        - light.bedroom_ceiling_2
        - light.bedroom_ceiling_3
        - light.bedroom_neopixel_light
        - light.bedroom_closet_led_power_supply_light
        - light.bedroom_bed_light
        - input_boolean.bedroom_light_automation_is_enabled
        - input_boolean.bedroom_blind_automation_is_enabled
        - cover.bedroom_blind_left
        - cover.bedroom_blind_center
        - cover.bedroom_blind_right
      # kitchen
        - binary_sensor.kitchen_sensor_motion_detected
        - binary_sensor.kitchen_sensor_door_sensor
        - sensor.kitchen_sensor_humidity
        - sensor.kitchen_sensor_temperature
        - light.kitchen_ceiling_light_light_switch
        - light.kitchen_led_spots_light
        - light.kitchen_light_controller_black_light
        - light.kitchen_light_controller_light_strip
        - input_boolean.kitchen_light_automation_is_enabled
      # bathroom
        - binary_sensor.bathroom_motion_detector
        - sensor.bathroom_sensor_actor_humidity
        - sensor.bathroom_sensor_actor_temperature
        - light.bathroom_sensor_actor_spots
        - light.bathroom_sensor_actor_light_strip
        - input_boolean.bathroom_light_automation_is_enabled
      # toilet
        - binary_sensor.toilet_motion_detector
        - sensor.toilet_temperature
        - light.toilet_lights
      # floor
        - binary_sensor.floor_sensor_actor_motion_detected
        - sensor.floor_sensor_actor_temperature
        - sensor.floor_sensor_actor_humidity
        - light.floor_light
        - light.floor_neo_pixel_light
      # balcony
        - sensor.balcony_sensor_actor_humidity
        - sensor.balcony_sensor_actor_temperature
        - light.balcony_sensor_actor_relay_light_1
        - light.balcony_sensor_actor_relay_light_2
      # office
        - light.office_workdesk_light
        - light.office_ceiling_light_1
        - light.office_ceiling_light_2
        - light.office_ceiling_light_3
        - switch.office_desk_plug
  - name: HASS Accessory Bridge
    port: 21065
    mode: accessory
    filter:
      include_domains:
        - media_player

input_boolean: !include_dir_merge_named input/input_boolean/
input_number: !include_dir_merge_named input/input_number/
input_select: !include_dir_merge_named input/input_select/
input_text: !include_dir_merge_named input/input_text/
input_datetime: !include_dir_merge_named input/input_datetime/

light bathroom: !include bathroom/lights.yaml
light balcony: !include balcony/lights.yaml
light toilet: !include toilet/lights.yaml
light floor: !include floor/lights.yaml
light living_room: !include living_room/lights.yaml
light kitchen: !include kitchen/lights.yaml
light bedroom: !include bedroom/lights.yaml
light office: !include office/lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.shell_command: debug
    custom_components.pyscript: info

lovelace:
  mode: storage
  dashboards:
    lovelace-overview:
      mode: yaml
      title: Overview
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: dashboards/overview.yaml
    lovelace-device:
      mode: yaml
      title: Devices
      icon: mdi:devices
      show_in_sidebar: true
      filename: dashboards/devices.yaml
    lovelace-administration:
      mode: yaml
      title: Administration
      icon: mdi:account-hard-hat
      show_in_sidebar: true
      filename: dashboards/administration.yaml
    lovelace-plants:
      mode: yaml
      title: Plants
      icon: mdi:flower-tulip-outline
      show_in_sidebar: true
      filename: dashboards/plants.yaml

monitor_docker:
  - name: Docker
    containers:
      - appdaemon
      - mosquitto
      - esphome
      - home-assistant
      - zigbee2mqtt
      - mariadb
      - homeassistant_influxdb_1
      - server_monitoring_renderer_1
      - server_monitoring_grafana_1
      - server_monitoring_node-exporter_1
      - server_monitoring_prometheus_1
    rename:
      appdaemon: AppDaemon
      mosquitto: Mosquitto
      esphome: ESPHome
      home-assistant: Homeassistant
      zigbee2mqtt: zigbee2MQTT
      homeassistant_influxdb_1: InfluxDB
      mariadb: Homeassistant MariaDB
      server_monitoring_grafana_1: Grafana
      server_monitoring_node-exporter_1: Server Node Exporter
      server_monitoring_prometheus_1: Prometheus
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - containers_paused
      - containers_stopped
      - containers_cpu_percentage
      - containers_1cpu_percentage
      - containers_memory
      - containers_memory_percentage
      - state
      - status
      - memory
      - memory_percentage
      - health
      - uptime
      - image
      - cpu_percentage
      - 1cpu_percentage

mqtt:
  switch:
    - command_topic: "zigbee2mqtt/bridge/request/permit_join"
      name: "Zigbee2MQTT Main join"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: '{{ value_json.permit_join | lower }}'
      payload_on: "true"
      payload_off: "false"
  sensor:
    - name: Zigbee2MQTT Bridge state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless
    - name: Zigbee2MQTT Version
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.version }}"
      icon: mdi:zigbee
    - name: Coordinator Version
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.coordinator }}"
      icon: mdi:chip
    - name: Zigbee2mqtt Networkmap
      state_topic: zigbee2mqtt/bridge/response/networkmap
      value_template: >-
          {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      json_attributes_template: "{{ value_json.data.value | tojson }}"

notify ios:
  - name: iOS
    platform: group
    services:
      - service: mobile_app_iphone_von_robert

pyscript: !include pyscript_config.yaml

remote_homeassistant:
  instances:

script: !include scripts.yaml

scene: !include scenes.yaml
scene bathroom: !include bathroom/scenes.yaml
scene bedroom: !include bedroom/scenes.yaml
scene balcony: !include balcony/scenes.yaml
scene floor: !include floor/scenes.yaml
scene kitchen: !include kitchen/scenes.yaml
scene living_room: !include living_room/scenes.yaml
scene office: !include office/scenes.yaml
scene toilet: !include toilet/scenes.yaml

sensor bathroom: !include bathroom/sensors.yaml
sensor toilet: !include toilet/sensors.yaml
sensor kitchen: !include kitchen/sensors.yaml
sensor general: !include general/sensors.yaml

switch kitchen: !include kitchen/switches.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

template: !include_dir_merge_list templates/

timer:
  bathroom_light_turn_off_timer:
    name: Bathroom Light Turnout Timer    
  bedroom_light_turn_off_timer:
    name: Bedroom Light Turnout Timer    
  living_room_tv_auto_off:
    name: Living Room Auto Off Timer
  workstation_power_control:
    name: Workstation Power Control Timer
  office_light_turn_off_timer:
    name: Office Light Turnout Timer
  toilet_light_turn_off_timer:
    name: Toilet Light Turnout Timer
  floor_light_turn_off_timer:
    name: Floor Light Turnout Timer
  kitchen_light_turn_off_timer:
    name: Kitchen Light Turnout Timer
  living_room_light_turn_off_timer:
    name: Living Room Light Turnout Timer
  living_touch_screen_back_light_turn_off_timer:
    name: Living Room Touch Screen Back Light Timer
  zigbee_permit_join:
    name: Time remaining
    duration: 120

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 10
  - name: Shopping
    latitude: !secret shopping_latitude
    longitude: !secret shopping_longitude
    radius: 23
