default_config:

homeassistant:
  elevation: 117
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

tts:
  - platform: google_translate

alert: !include_dir_merge_named alerts/

automation bedroom: !include bedroom/automations.yaml
automation general_zigbee: !include general/zigbee2mqtt_automations.yaml
automation general_shopping: !include general/shopping_automations.yaml
automation home_server: !include general/home_server_automations.yaml

binary_sensor general: !include general/binary_sensors.yaml 
binary_sensor general_esphome: !include general/esphome_binary_sensors.yaml
binary_sensor bathroom: !include bathroom/binary_sensors.yaml
binary_sensor bedroom: !include bedroom/binary_sensors.yaml
binary_sensor toilet: !include toilet/binary_sensors.yaml

device_tracker:
  - platform: luci
    host: RPNRouter
    username: !secret luci_login
    password: !secret luci_password

group: !include_dir_merge_named groups/

influxdb:
  host: !secret influx_host
  database: home_assistant
  username: !secret influx_user
  password: !secret influx_password

http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_certificate_key_path
  ip_ban_enabled: true
  login_attempts_threshold: 5

homekit:
  - filter:
      include_domains:
        - binary_sensor
        - light
        #- media_player
        - scene
        - sensor
        - switch
        - input_boolean
      exclude_entity_globs:
        - binary_sensor.*_connection_status
        - binary_sensor.*_update_available
        - binary_sensor.*_led_indication
        - binary_sensor.lenovo_new_gen_*
        - binary_sensor.living_room_tv_*
        - binary_sensor.pixel_4a_*
        - sensor.*_connected_bssid
        - sensor.*_connected_ssid
        - sensor.*_ip_address
        - sensor.*_mac_wifi_address
        - sensor.*_uptime
        - sensor.*_wifi_signal
        - sensor.*_linkquality
        - sensor.*_update_state
        - sensor.*_battery_level
        - sensor.*_battery_state*
        - sensor.*_battery
        - sensor.*_illuminance_lux
        - sensor.*_motion_sensitivity
        - sensor.*_occupancy_timeout
        - sensor.*_action
        - sensor.download_*
        - sensor.iphone_von_robert_*
        - sensor.pixel_4a_*
        - sensor.*_last_watering_duration
        - sensor.*_last_watering_time_stamp
        - sensor.*_raw_value
        - sensor.zigbee2mqtt_*
        - sensor.uptime_sensor*
        - sensor.hue_motion_sensor_*_temperature
        - switch.*_shutdown
        - input_boolean.*_automatic_scene_mode_enabled
      include_entities:
        - light.living_room_sensor_actor_2_light_strings
      exclude_entities:
        - binary_sensor.robert_think_pad_is_on
        - binary_sensor.robert_work_laptop_is_on
        - binary_sensor.shopping_list_has_items
        - binary_sensor.updater
        - binary_sensor.work_laptop_activity
        - binary_sensor.workday_sensor
        - binary_sensor.hue_motion_sensor_2_occupancy
        - light.my_custom_light
        - sensor.cert_expiry_timestamp_robertnator_duckdns_org
        - sensor.coordinator_version
        - sensor.data_from_topic
        - sensor.hacs
        - sensor.iphone_von_robert_activity
        - sensor.iphone_von_robert_average_active_pace
        - sensor.iphone_von_robert_battery_state
        - sensor.kitchen_mqtt_lcd_display_display_topic
        - sensor.robert_thinkpad_running
        - sensor.shopping_list
        - sensor.bathroom_temperature
        - switch.lenovo_new_gen_backup_switch_switch
        - switch.lenovo_new_gen_suspend_switch
        - switch.zigbee2mqtt_main_join
        - input_boolean.bedroom_closet_light_was_turned_off_before
        - input_boolean.zigbee2mqtt_force_remove
        - input_boolean.touch_screen_back_light_automatic_enabled
  - name: HASS Accessory Bridge
    port: 21065
    mode: accessory
    filter:
      include_domains:
        - media_player

input_boolean: !include_dir_merge_named input/input_boolean/
input_number: !include_dir_merge_named input/input_number/
input_select: !include_dir_merge_named input/input_select/
input_text: !include_dir_merge_named input/input_text/
input_datetime: !include_dir_merge_named input/input_datetime/

light bathroom: !include bathroom/lights.yaml
light balcony: !include balcony/lights.yaml
light toilet: !include toilet/lights.yaml
light floor: !include floor/lights.yaml
light living_room: !include living_room/lights.yaml
light kitchen: !include kitchen/lights.yaml
light bedroom: !include bedroom/lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.shell_command: debug
    custom_components.pyscript: info

lovelace:
  mode: storage
  dashboards:
    lovelace-overview:
      mode: yaml
      title: Overview
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: dashboards/overview.yaml
    lovelace-device:
      mode: yaml
      title: Devices
      icon: mdi:devices
      show_in_sidebar: true
      filename: dashboards/devices.yaml
    lovelace-administration:
      mode: yaml
      title: Administration
      icon: mdi:account-hard-hat
      show_in_sidebar: true
      filename: dashboards/administration.yaml
    lovelace-plants:
      mode: yaml
      title: Plants
      icon: mdi:flower-tulip-outline
      show_in_sidebar: true
      filename: dashboards/plants.yaml
media_player:
  - platform: androidtv
    host: !secret tv_living_room_ip
    name: "TV LivingRoom"

monitor_docker:
  - name: Docker
    containers:
      - appdaemon
      - mosquitto
      - esphome
      - home-assistant
      - zigbee2mqtt
      - mariadb
      - homeassistant_influxdb_1
      - server_monitoring_renderer_1
      - server_monitoring_grafana_1
      - server_monitoring_node-exporter_1
      - server_monitoring_prometheus_1
    rename:
      appdaemon: AppDaemon
      mosquitto: Mosquitto
      esphome: ESPHome
      home-assistant: Homeassistant
      zigbee2mqtt: zigbee2MQTT
      homeassistant_influxdb_1: InfluxDB
      mariadb: Homeassistant MariaDB
      server_monitoring_grafana_1: Grafana
      server_monitoring_node-exporter_1: Server Node Exporter
      server_monitoring_prometheus_1: Prometheus
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - containers_paused
      - containers_stopped
      - containers_cpu_percentage
      - containers_1cpu_percentage
      - containers_memory
      - containers_memory_percentage
      - state
      - status
      - memory
      - memory_percentage
      - health
      - uptime
      - image
      - cpu_percentage
      - 1cpu_percentage
mqtt:
  broker: rpn-home-server
  username: !secret mqtt_username
  password: !secret mqtt_password

notify ios:
  - name: iOS
    platform: group
    services:
      - service: mobile_app_iphone_von_robert

pyscript: !include pyscript/config.yaml

remote_homeassistant:
  instances:

script: !include scripts.yaml

scene: !include scenes.yaml
scene bathroom: !include bathroom/scenes.yaml
scene bedroom: !include bedroom/scenes.yaml
scene balcony: !include balcony/scenes.yaml
scene floor: !include floor/scenes.yaml
scene kitchen: !include kitchen/scenes.yaml
scene living_room: !include living_room/scenes.yaml
scene toilet: !include toilet/scenes.yaml

sensor bathroom: !include bathroom/sensors.yaml
sensor toilet: !include toilet/sensors.yaml
sensor kitchen: !include kitchen/sensors.yaml
sensor general: !include general/sensors.yaml
sensor general_zigbee2mqtt: !include general/zigbee2mqtt_sensors.yaml

switch general: !include general/switches.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

template: !include_dir_merge_list templates/

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 10
  - name: Shopping
    latitude: !secret shopping_latitude
    longitude: !secret shopping_longitude
    radius: 23
