
default_config:

homeassistant:
  customize: !include customize.yaml

tts:
  - platform: google_translate

alert: !include_dir_merge_named alerts/

automation living_room: !include living_room/automations.yaml
automation bedroom: !include bedroom/automations.yaml
automation balcony: !include balcony/automations.yaml
automation kitchen: !include kitchen/automations.yaml

binary_sensor general: !include general/binary_sensors.yaml 
binary_sensor bedroom: !include bedroom/binary_sensors.yaml
binary_sensor toilet: !include toilet/binary_sensors.yaml
binary_sensor kitchen: !include kitchen/binary_sensors.yaml

group: !include_dir_merge_named groups/

input_boolean: !include_dir_merge_named input/input_boolean/
input_number: !include_dir_merge_named input/input_number/
input_select: !include_dir_merge_named input/input_select/
input_text: !include_dir_merge_named input/input_text/
input_datetime: !include_dir_merge_named input/input_datetime/

light balcony: !include balcony/lights.yaml
light toilet: !include toilet/lights.yaml
light floor: !include floor/lights.yaml
light living_room: !include living_room/lights.yaml
light kitchen: !include kitchen/lights.yaml
light bedroom: !include bedroom/lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.shell_command: debug

lovelace:
  mode: storage
  dashboards:
    lovelace-light:
      mode: yaml
      title: Lights
      icon: mdi:ceiling-light
      show_in_sidebar: true
      filename: dashboards/lights.yaml
    lovelace-device:
      mode: yaml
      title: Devices
      icon: mdi:devices
      show_in_sidebar: true
      filename: dashboards/devices.yaml

media_player:
  - platform: androidtv
    host: 172.22.24.187
    name: "TV LivingRoom"
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

mqtt:
  broker: 127.0.0.1

notify ios:
  - name: iOS
    platform: group
    services:
      - service: mobile_app_iphone_von_robert

script: !include scripts.yaml

scene: !include scenes.yaml
scene bedroom: !include bedroom/scenes.yaml
scene balcony: !include balcony/scenes.yaml
scene floor: !include floor/scenes.yaml
scene kitchen: !include kitchen/scenes.yaml
scene toilet: !include toilet/scenes.yaml

sensor bedroom: !include bedroom/sensors.yaml 
sensor kitchen: !include kitchen/sensors.yaml
sensor living_room: !include living_room/sensors.yaml
sensor toilet: !include toilet/sensors.yaml

shell_command:
  truncate_file: >
    truncate -s 0 {{ file_path }}
  write_variable_content_to_file: >
    /bin/bash -c "echo '{{ content }}' >> {{ target_file }}"
