
default_config:

homeassistant:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 117
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

tts:
  - platform: google_translate

alert: !include_dir_merge_named alerts/

automation bedroom: !include bedroom/automations.yaml
automation kitchen: !include kitchen/automations.yaml

binary_sensor general: !include general/binary_sensors.yaml 
binary_sensor bathroom: !include bathroom/binary_sensors.yaml
binary_sensor bedroom: !include bedroom/binary_sensors.yaml
binary_sensor toilet: !include toilet/binary_sensors.yaml
binary_sensor kitchen: !include kitchen/binary_sensors.yaml
binary_sensor living_room: !include living_room/binary_sensors.yaml

camera kitchen_grafana: !include cameras/grafana_kitchen_graphs.yaml

device_tracker:
  - platform: luci
    host: RPNRouter
    username: !secret luci_login
    password: !secret luci_password

group: !include_dir_merge_named groups/

influxdb:
  host: !secret influx_host

http:
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_certificate_key_path
  ip_ban_enabled: true
  login_attempts_threshold: 5

input_boolean: !include_dir_merge_named input/input_boolean/
input_number: !include_dir_merge_named input/input_number/
input_select: !include_dir_merge_named input/input_select/
input_text: !include_dir_merge_named input/input_text/
input_datetime: !include_dir_merge_named input/input_datetime/

light bathroom: !include bathroom/lights.yaml
light balcony: !include balcony/lights.yaml
light toilet: !include toilet/lights.yaml
light floor: !include floor/lights.yaml
light living_room: !include living_room/lights.yaml
light kitchen: !include kitchen/lights.yaml
light bedroom: !include bedroom/lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.shell_command: debug

lovelace:
  mode: storage
  dashboards:
    lovelace-light:
      mode: yaml
      title: Lights
      icon: mdi:ceiling-light
      show_in_sidebar: true
      filename: dashboards/lights.yaml
    lovelace-device:
      mode: yaml
      title: Devices
      icon: mdi:devices
      show_in_sidebar: true
      filename: dashboards/devices.yaml
    lovelace-plants:
      mode: yaml
      title: Plants
      icon: mdi:flower-tulip-outline
      show_in_sidebar: true
      filename: dashboards/plants.yaml
media_player:
  - platform: androidtv
    host: !secret tv_living_room_ip
    name: "TV LivingRoom"

mqtt:
  broker: rpn-home-server
  username: !secret mqtt_username
  password: !secret mqtt_password

notify ios:
  - name: iOS
    platform: group
    services:
      - service: mobile_app_iphone_von_robert

script: !include scripts.yaml

scene: !include scenes.yaml
scene bathroom: !include bathroom/scenes.yaml
scene bedroom: !include bedroom/scenes.yaml
scene balcony: !include balcony/scenes.yaml
scene floor: !include floor/scenes.yaml
scene kitchen: !include kitchen/scenes.yaml
scene living_room: !include living_room/scenes.yaml
scene toilet: !include toilet/scenes.yaml

sensor bathroom: !include bathroom/sensors.yaml
sensor bedroom: !include bedroom/sensors.yaml 
sensor toilet: !include toilet/sensors.yaml
sensor kitchen_grafana: !include kitchen/grafana_sensors.yaml


shell_command:
  truncate_file: >
    truncate -s 0 {{ file_path }}
  write_variable_content_to_file: >
    /bin/bash -c "echo '{{ content }}' >> {{ target_file }}"
