
default_config:

homeassistant:
  customize: !include customize.yaml

tts:
  - platform: google_translate

notify ios:
  - name: iOS
    platform: group
    services:
      - service: mobile_app_iphone_von_robert

input_boolean:
  bedroom_closet_light_was_turned_off_before:
    initial: false
  fride_door_was_left_open:
    initial: false

alert:
  fridge_was_left_open_alert:
    name: Kühlschrank wurde offen gelassen!
    done_message: Kühlschrank wieder geschlossen
    entity_id: binary_sensor.fride_door_open_to_long
    state: 'on'
    repeat: 1
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios
  bedroom_sensor_1_is_offline:
    name: Bedroom Sensor 1 offline
    done_message: Bedroom Sensor 1 online again
    entity_id: binary_sensor.bedroom_sensor_1_ping
    state: 'off'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios
  living_room_ikea_light_1_is_offline:
    name: Living Room Ikea Light 1 offline
    done_message: Living Room Ikea Light 1 online again
    entity_id: binary_sensor.former_ikea_light_ping
    state: 'off'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios
  balcony_sensor_actor_1_is_offline:
    name: Balcony Sensor/Actor 1 offline
    done_message: Balcony Sensor/Actor 1 online again
    entity_id: binary_sensor.balcony_sensor_actor_1_ping
    state: 'off'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios
  floor_sensor_actor_1_is_offline:
    name: Floor Sensor/Actor 1 offline
    done_message: Floor Sensor/Actor 1 online again
    entity_id: binary_sensor.floor_sensor_actor_1_ping
    state: 'off'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios
  living_room_sensor_actor_1_is_offline:
    name: Living Room Sensor/Actor 1 offline
    done_message: Living Room Sensor/Actor 1 online again
    entity_id: binary_sensor.living_room_sensor_actor_1_ping
    state: 'off'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios
  kitchen_actor_1_is_offline:
    name: Kitchen Actor 1 offline
    done_message: Kitchen Actor 1 online again
    entity_id: binary_sensor.kitchen_actor_1_ping
    state: 'off'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios
  kitchen_sensor_1_is_offline:
    name: Kitchen Sensor 1 offline
    done_message: Kitchen Sensor 1 online again
    entity_id: binary_sensor.kitchen_actor_1_ping
    state: 'off'
    repeat: 30
    can_acknowledge: true
    skip_first: false
    notifiers:
      - ios


light balcony: !include balcony/lights.yaml
light toilet: !include toilet/lights.yaml
light floor: !include floor/lights.yaml
light living_room: !include living_room/lights.yaml
light kitchen: !include kitchen/lights.yaml
light bedroom: !include bedroom/lights.yaml

sensor bedroom: !include bedroom/sensors.yaml 
sensor toilet: !include toilet/sensors.yaml

binary_sensor toilet: !include toilet/binary_sensors.yaml
binary_sensor kitchen: !include kitchen/binary_sensors.yaml

group: !include_dir_merge_named groups/

automation living_room: !include living_room/automations.yaml
automation toilet: !include toilet/automations.yaml
automation bedroom: !include bedroom/automations.yaml
automation balcony: !include balcony/automations.yaml
automation kitchen: !include kitchen/automations.yaml
automation floor: !include floor/automations.yaml

script: !include scripts.yaml
scene: !include scenes.yaml

scene bedroom: !include bedroom/scenes.yaml
scene balcony: !include balcony/scenes.yaml
scene kitchen: !include kitchen/scenes.yaml
scene toilet: !include toilet/scenes.yaml

input_number:
  bedroom_light_brightness:
    name: Bedroom Light Brightness Slider
    initial: 39
    min: 39
    max: 255
    step: 36
  kitchen_light_brightness:
    name: Kitchen Light Brightness Slider
    initial: 120
    min: 0
    max: 255
    step: 15

input_select:
  bedroom_light_scene:
    options:
      - 'scene.bedroom_romantic'
      - 'scene.bedroom_relaxed'
      - 'scene.bedroom_bright'
      - 'scene.bedroom_work_1'
      - 'scene.bedroom_dimmed'
      - 'scene.bedroom_night_light'
      - 'scene.bedroom_1313'
    initial: 'scene.bedroom_bright'
  balcony_light_scene:
    options:
      - 'scene.balcony_bright'
      - 'scene.balcony_indirect'
    initial: 'scene.balcony_indirect'
  kitchen_light_scene:
    options:
      - 'scene.kitchen_cooking_1'
      - 'scene.kitchen_cooking_2'
      - 'scene.kitchen_indirect_light_1'
      - 'scene.kitchen_indirect_light_2'
      - 'scene.kitchen_night_light_1'
    initial: 'scene.kitchen_cooking_1'
  toilet_light_scene:
    options:
      - 'scene.toilet_night_light'
      - 'scene.toilet_day_light'
    initial: 'scene.toilet_day_light'


logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info

mqtt:
  broker: 127.0.0.1

media_player:
  - platform: androidtv
    host: 172.22.24.187
    name: "TV LivingRoom"
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037