default_config:

homeassistant:
  elevation: 117
  time_zone: Europe/Berlin
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp

tts:
  - platform: google_translate

alert: !include_dir_merge_named alerts/

automation bedroom: !include bedroom/automations.yaml
automation bathroom: !include bathroom/automations.yaml
automation general_shopping: !include general/shopping_automations.yaml
automation home_server: !include general/home_server_automations.yaml
automation zigbee2mqtt: !include zigbee2mqtt/automations.yaml

binary_sensor general: !include general/binary_sensors.yaml 
binary_sensor bedroom: !include bedroom/binary_sensors.yaml

fan bathroom: !include bathroom/fan.yaml

group: !include_dir_merge_named groups/

influxdb:
  host: !secret influx_host
  database: home_assistant
  username: !secret influx_user
  password: !secret influx_password
  exclude:
    entities:
      - sensor.active_dhcp_leases
      - sensor.known_devices
      - sensor.wifi_connections_sensor

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - ::1

homekit:
  - filter:
      include_entities:
      # living room
        - binary_sensor.living_room_motion_sensor_occupancy
        - input_boolean.living_room_light_automation_is_enabled
        - light.living_room_ceiling_light
        - light.living_room_standing_light_1
        - light.living_room_standing_light_2
        - light.living_room_sensor_actor_2_light_strings
        - light.living_room_hue_light_bulb
        - light.living_room_globe_light
        - light.living_room_round_light
        - sensor.living_room_sensor_actor_2_humidity
        - sensor.living_room_sensor_actor_2_light_intensity
        - sensor.living_room_sensor_actor_2_temperature
      # bathroom & toilet
        - binary_sensor.bathroom_sensor_actor_motion_detected
        - fan.bathroom_fan
        - input_boolean.bathroom_light_automation_is_enabled
        - light.bathroom_sensor_actor_light
        - light.bathroom_indirect_light
        - sensor.bathroom_sensor_actor_humidity
        - sensor.bathroom_sensor_actor_light_intensity
        - sensor.bathroom_sensor_actor_temperature
      # bedroom
        - binary_sensor.bedroom_sensor_motion_detected
        - cover.bedroom_blind_left
        - cover.bedroom_blind_right
        - input_boolean.bedroom_light_automation_is_enabled
        - input_boolean.bedroom_blind_automation_is_enabled
        - light.bedroom_bed_light
        - light.bedroom_ceiling_light
        - light.bedroom_neopixel_light
        - light.bedroom_workdesk_light
        - sensor.bedroom_sensor_humidity
        - sensor.bedroom_sensor_light_intensity
        - sensor.bedroom_sensor_temperature
        - switch.bedroom_desk_plug_1
        - switch.bedroom_desk_plug_2
      # kitchen
        - binary_sensor.kitchen_sensor_actor_motion_detected
        - input_boolean.kitchen_light_automation_is_enabled
        - light.kitchen_ceiling_light_light_switch
        - light.kitchen_entrance_light
        - light.kitchen_led_spots_light
        - light.kitchen_shelf_light
        - light.kitchen_cabinet_light_1
        - light.kitchen_cabinet_light_2
        - light.kitchen_neo_pixel_light
        - sensor.kitchen_sensor_actor_humidity
        - sensor.kitchen_sensor_actor_light_intensity
        - sensor.kitchen_sensor_actor_temperature
  - name: HASS Accessory Bridge
    port: 21065
    mode: accessory
    filter:
      include_domains:
        - media_player

input_boolean: !include_dir_merge_named input/input_boolean/
input_number: !include_dir_merge_named input/input_number/
input_select: !include_dir_merge_named input/input_select/
input_text: !include_dir_merge_named input/input_text/
input_datetime: !include_dir_merge_named input/input_datetime/

light bathroom: !include bathroom/lights.yaml
light bedroom: !include bedroom/lights.yaml
light kitchen: !include kitchen/lights.yaml
light living_room: !include living_room/lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.components.shell_command: debug
    custom_components.pyscript: info

lovelace:
  mode: storage
  dashboards:
    lovelace-overview:
      mode: yaml
      title: Overview
      icon: mdi:home-assistant
      show_in_sidebar: true
      filename: dashboards/overview.yaml
    lovelace-device:
      mode: yaml
      title: Devices
      icon: mdi:devices
      show_in_sidebar: true
      filename: dashboards/devices.yaml
    lovelace-administration:
      mode: yaml
      title: Administration
      icon: mdi:account-hard-hat
      show_in_sidebar: true
      filename: dashboards/administration.yaml


monitor_docker:
  - name: Docker
    containers:
      - mosquitto
      - esphome
      - home-assistant
      - zigbee2mqtt
      - mariadb
      - homeassistant_influxdb_1
      - server_monitoring_renderer_1
      - server_monitoring_grafana_1
      - server_monitoring_node-exporter_1
      - server_monitoring_prometheus_1
    rename:
      mosquitto: Mosquitto
      esphome: ESPHome
      home-assistant: Homeassistant
      zigbee2mqtt: zigbee2MQTT
      homeassistant_influxdb_1: InfluxDB
      mariadb: Homeassistant MariaDB
      server_monitoring_grafana_1: Grafana
      server_monitoring_node-exporter_1: Server Node Exporter
      server_monitoring_prometheus_1: Prometheus
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - containers_paused
      - containers_stopped
      - containers_cpu_percentage
      - containers_1cpu_percentage
      - containers_memory
      - containers_memory_percentage
      - state
      - status
      - memory
      - memory_percentage
      - health
      - uptime
      - image
      - cpu_percentage
      - 1cpu_percentage

mqtt:
  switch:
    - command_topic: "zigbee2mqtt/bridge/request/permit_join"
      name: "Zigbee2MQTT Main join"
      state_topic: "zigbee2mqtt/bridge/info"
      value_template: '{{ value_json.permit_join | lower }}'
      payload_on: "true"
      payload_off: "false"
  sensor:
    - name: Zigbee2MQTT Bridge state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless
    - name: Zigbee2MQTT Version
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.version }}"
      icon: mdi:zigbee
    - name: Coordinator Version
      state_topic: "zigbee2mqtt/bridge/config"
      value_template: "{{ value_json.coordinator }}"
      icon: mdi:chip
    - name: Zigbee2mqtt Networkmap
      state_topic: zigbee2mqtt/bridge/response/networkmap
      value_template: >-
          {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
      json_attributes_topic: zigbee2mqtt/bridge/response/networkmap
      json_attributes_template: "{{ value_json.data.value | tojson }}"

notify ios:
  - name: iOS
    platform: group
    services:
      - service: mobile_app_iphone_von_robert

pyscript: !include pyscript_config.yaml

remote_homeassistant:
  instances:

script: !include scripts.yaml

scene bathroom: !include bathroom/scenes.yaml
scene bedroom: !include bedroom/scenes.yaml
scene kitchen: !include kitchen/scenes.yaml
scene living_room: !include living_room/scenes.yaml

sensor kitchen: !include kitchen/sensors.yaml
sensor general: !include general/sensors.yaml

switch bedroom: !include bedroom/switches.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

template: !include_dir_merge_list templates/

timer:
  bathroom_fan_turn_off_timer:
    name: Bathroom Fan Turn Off Timer
  bathroom_light_turn_off_timer:
    name: Bathroom Light Turnout Timer
  bedroom_light_turn_off_timer:
    name: Bedroom Light Turnout Timer    
  living_room_tv_auto_off:
    name: Living Room Auto Off Timer
  workstation_power_control:
    name: Workstation Power Control Timer
  kitchen_light_turn_off_timer:
    name: Kitchen Light Turnout Timer
  living_room_light_turn_off_timer:
    name: Living Room Light Turnout Timer
  zigbee_permit_join:
    name: Time remaining
    duration: 120

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 10
