allow_all_imports: true
hass_is_global: true
apps:
  home_server_update:
    update_log: /config/tmp/apt_update.log
  
  ikea_button_controller:
    - kitchen_light_button:
        entity: light.kitchen_lights
        switch_sensor: sensor.ikea_kitchen_smart_button_action
        scene_input_select: input_select.kitchen_automatic_light_scene_generated
        dim_step_size: input_number.kitchen_smart_button_dim_step_size
        scene_prefix: Kitchen
    - bedroom_light_button:
        entity: light.all_bedroom_lights
        switch_sensor: sensor.ikea_bedroom_smart_button_action
        scene_input_select: input_select.bedroom_automatic_light_scene_generated
        dim_step_size: input_number.bedroom_smart_button_dim_step_size
        scene_prefix: Bedroom
    - living_room_light_button:
        entity: light.living_room_lights
        switch_sensor: sensor.ikea_living_room_smart_button_action
        scene_input_select: input_select.living_room_automatic_light_scene_generated
        dim_step_size: input_number.living_room_smart_button_dim_step_size
        scene_prefix: Living Room

  activity_based_entity_control: 
    - !include light_control.yaml
    - workstation_power_control:
        entity: switch.work_station_power_switch
        motion_sensor_entity: binary_sensor.bedroom_workstation_power_required
        automation_enabled_entity: input_boolean.bedroom_workstation_toggle_automatic_enabled
        turn_off_timeout_entity: input_number.bedroom_workstation_power_turn_off_timeout
        turn_off_timer_entity: timer.workstation_power_control
    - living_room_tv_auto_off:
        entity: media_player.tv_livingroom
        motion_sensor_entity: binary_sensor.living_room_tv_is_playing
        automation_enabled_entity: input_boolean.living_room_turn_off_tv_when_idle_automation_enabled
        turn_off_timeout_entity: input_number.tv_living_room_idle_turn_off_timeout
        turn_off_timer_entity: timer.living_room_tv_auto_off
        skip_turn_on: true

global:
  esp_home_automations:
    esp_home_base_path: "/home/robert/docker/homeassistant/volumes/homeassistant/esphome"
  ssh:
    ssh_key: "/config/.ssh/id_rsa"
  host_server:
    ssh_key: "/config/.ssh/id_rsa"
    ssh_login: "robert@rpn-home-server"
    ssh_sudo: !secret host_sudo
    home_assistant_docker_compose: "/home/robert/docker/homeassistant/docker-compose.yaml"
    server_monitoring_docker_compose: "/home/robert/docker/server_monitoring/docker-compose.yaml"
  openwrt:
    ssh_login: "root@RPNRouter"