- alias: Update Home Server
  trigger:
    - platform: state
      entity_id: binary_sensor.home_server_updates_available
      to: "on"
  action:
  - service: shell_command.update_home_server
  - service: persistent_notification.create
    data:
      message: "Check log files to see results"
      title: "Home-Sever update executed"