- platform: mqtt
  name: Zigbee2MQTT Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
- platform: mqtt
  name: Zigbee2MQTT Version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.version }}"
  icon: mdi:zigbee
- platform: mqtt
  name: Coordinator Version
  state_topic: "zigbee2mqtt/bridge/config"
  value_template: "{{ value_json.coordinator }}"
  icon: mdi:chip
- platform: mqtt
  name: Zigbee2mqtt Networkmap
  state_topic: zigbee2mqtt/bridge/networkmap/raw
  value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
  json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

- platform: command_line
  name: home_server_update_state
  command: /config/scripts/update_sensor.py
  value_template: "{{ value_json['total_updates'] }}"
  json_attributes: 
    - total_updates
    - security_updates