- platform: command_line
  name: home_server_update_state
  command: /config/pyscript/sensors/update_sensor.py
  value_template: "{{ value_json['total_updates'] }}"
  json_attributes:
    - total_updates
    - security_updates

- platform: command_line
  name: promethues_up_query_state
  command: /config/pyscript/sensors/prometheus_up_sensor.py

- platform: command_line
  name: wifi_connections_sensor
  command: /config/pyscript/sensors/wifi_connections_sensor.py
  value_template: "{{ value_json['connection_count'] }}"
  json_attributes:
    - connections

- platform: command_line
  name: home_server_diskusage
  command: /config/pyscript/sensors/prometheus_disk_usage_sensor.py
  value_template: "{{ value_json['disk_usage'] }}"
  unit_of_measurement: "%"
  json_attributes:
    - available_space
    - filesystem_size

- platform: command_line
  name: unknown_wifi_devices
  value_template: "{{ value_json['devices'] | length }}"
  command: /config/pyscript/sensors/unknown_wifi_connections_sensor.py
  json_attributes:
    - devices

- platform: command_line
  name: known_devices
  value_template: "{{ value_json['count'] }}"
  command: /config/pyscript/sensors/known_devices_sensor.py
  json_attributes:
    - devices

- platform: command_line
  name: active_dhcp_leases
  value_template: "{{ value_json['count'] }}"
  command: /config/pyscript/sensors/active_dhcp_leases_sensor.py
  json_attributes:
    - leases
