- platform: command_line
  name: home_server_update_state
  command: /config/scripts/update_sensor.py
  value_template: "{{ value_json['total_updates'] }}"
  json_attributes: 
    - total_updates
    - security_updates

- platform: command_line
  name: homeassistant_version
  command: /config/scripts/./homeassistant_version_sensor.py

- platform: command_line
  name: promethues_up_query_state
  command: /config/scripts/./prometheus_up_sensor.py
