- alias: Notify Shopping List
  trigger:
    - platform: zone
      entity_id: person.robert
      zone: zone.shopping
      event: enter
  condition: "{{ states('binary_sensor.shopping_list_has_items') == 'on' }}"
  action:
  - service: notify.mobile_app_iphone_von_robert
    data_template:
      title: Einkaufsliste
      message: "{{ states('sensor.shopping_list').split(',') | join(', ') }}"
      target: 'https://robertnator.duckdns.org/shopping-list'
