- alias: Turn on kitchen lights on smart button toggle
  trigger:
    - platform: state
      entity_id: sensor.ikea_kitchen_smart_button_action
      to: 'toggle'
  action:
    - service: light.toggle
      entity_id: light.kitchen_lights

- alias: Change To Previous Kitchen Scene On Smart Button Event
  trigger:
    - platform: state
      entity_id: sensor.ikea_kitchen_smart_button_action
      to: 'arrow_left_click'
  action:
    - service: input_select.select_previous
      entity_id: input_select.kitchen_light_scene
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states('input_select.kitchen_light_scene') }}"

- alias: Change To Next Kitchen Scene On Smart Button Event
  trigger:
    - platform: state
      entity_id: sensor.ikea_kitchen_smart_button_action
      to: 'arrow_right_click'
  action:
    - service: input_select.select_next
      entity_id: input_select.kitchen_light_scene
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states('input_select.kitchen_light_scene') }}"

- alias: Increase/Decrease Kitchen Light Brightness On Smart Button Event
  trigger:
    - platform: state
      entity_id: sensor.ikea_kitchen_smart_button_action
      to: 'brightness_up_click'
    - platform: state
      entity_id: sensor.ikea_kitchen_smart_button_action
      to: 'brightness_down_click'
  action:
    - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'brightness_up_click'}}"
        sequence:
          - service: input_number.increment
            entity_id: input_number.kitchen_light_brightness
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'brightness_down_click'}}"
        sequence:
          - service: input_number.decrement
            entity_id: input_number.kitchen_light_brightness
    - service: light.turn_on
      entity_id: light.kitchen_dimmable_lights
      data_template:
        brightness: "{{ states('input_number.kitchen_light_brightness') | int }}"

- alias: Turn on kitchen lights when there is movement
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_detector
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.kitchen_outside_light_intensity
      below: 750
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
  action:
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states('input_select.kitchen_light_scene') }}"

- alias: Turn off kitchen lights when there is no movement
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_detector
    to: 'off'
    for:
      seconds: 100
  action:
    - service: light.turn_off
      entity_id: light.kitchen_lights