- alias: Set Alarm when Fridge is open
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_sensor_door_sensor
      to: 'on'
      for:
        seconds: 45
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.fride_door_was_left_open
    - service: script.turn_on
      entity_id: script.let_light_blink
      data:
        variables:
          light_entity_id: light.kitchen_ceiling_light_1_relais_light_1
          observed_input_boolean: input_boolean.fride_door_was_left_open

- alias: Reset Alarm when Fridge is closed
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_sensor_door_sensor
      to: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.fride_door_was_left_open
    - service: script.turn_off
      entity_id: script.let_light_blink
