- platform: mqtt
  name: "Kitchen Motion Detector 1"
  state_topic: "kitchen/motion"
  off_delay: 0
  payload_on: "on"
  payload_off: "off"
- platform: template
  sensors:
    kitchen_motion_detector:
      device_class: motion
      friendly_name: "Kitchen Motion Detector"
      value_template: >-
        {{ is_state("binary_sensor.kitchen_motion_detector_1", "on") }}