- platform: mqtt
  name: "Kitchen Ceiling Light"
  state_topic: "kitchen/ceiling_light/status"
  command_topic: "kitchen/ceiling_light/set"
- platform: group
  name: Kitchen Indirect Lights
  entities:
    - light.kitchen_actor_1_rgb
    - light.kitchen_led_spots_light
    - light.kitchen_actor_1_relais_switch
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_ceiling_light
    - light.kitchen_actor_1_rgb
    - light.kitchen_led_spots_light
    - light.kitchen_actor_1_relais_switch