- platform: mqtt
  name: "Kitchen Temperature"
  state_topic: "kitchen/temperature"
  payload_available: "online"
  payload_not_available: "offline"
  icon: 'mdi:thermometer'
- platform: mqtt
  name: "Kitchen Humidity"
  state_topic: "kitchen/humidity"
  payload_available: "online"
  payload_not_available: "offline"
  icon: 'mdi:water-percent'
- platform: mqtt
  name: "Kitchen Outside Light Intensity"
  state_topic: "kitchen/outside_light_intensity"
  payload_available: "online"
  payload_not_available: "offline"
  icon: 'mdi:white-balance-sunny'