- platform: template
  sensors:
    kitchen_left_plant_last_watering_duration:
      value_template: >
        {% set uptime = as_timestamp(now()) - as_timestamp(states('sensor.kitchen_left_plant_last_watering_time_stamp')) | int - 60*60 %}
        {% set days = (uptime / 86400) | int %}
        {%- if days > 0 -%}
        {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S') }}
        {%- else -%}
          {{ uptime | int | timestamp_custom('%H:%M:%S') }}
        {%- endif -%}
    kitchen_right_plant_last_watering_duration:
      value_template: >
        {% set uptime = as_timestamp(now()) - as_timestamp(states('sensor.kitchen_right_plant_last_watering_time_stamp')) | int - 60*60 %}
        {% set days = (uptime / 86400) | int %}
        {%- if days > 0 -%}
        {{ days }} days, {{ (uptime - (days * 86400)) | int | timestamp_custom('%H:%M:%S') }}
        {%- else -%}
          {{ uptime | int | timestamp_custom('%H:%M:%S') }}
        {%- endif -%}
    kitchen_left_plant_age_in_days:
      value_template: >
        {{ ((now() | as_timestamp - states("input_datetime.left_plant_planting_date") | as_timestamp) / (24*60*60)) | int }}
      unit_of_measurement: days
      icon_template: mdi:sort-clock-descending-outline
    kitchen_middle_plant_age_in_days:
      value_template: >
        {{ ((now() | as_timestamp - states("input_datetime.middle_plant_planting_date") | as_timestamp) / (24*60*60)) | int }}
      unit_of_measurement: days
      icon_template: mdi:sort-clock-descending-outline
    kitchen_middle_back_plant_age_in_days:
      value_template: >
        {{ ((now() | as_timestamp - states("input_datetime.middle_back_plant_planting_date") | as_timestamp) / (24*60*60)) | int }}
      unit_of_measurement: days
      icon_template: mdi:sort-clock-descending-outline

    kitchen_right_plant_age_in_days:
      value_template: >
        {{ ((now() | as_timestamp - states("input_datetime.right_plant_planting_date") | as_timestamp) / (24*60*60)) | int }}
      unit_of_measurement: days
      icon_template: mdi:sort-clock-descending-outline
- platform: command_line
  name: shopping_list
  command: /config/scripts/shopping_list.py
