
turn_on_lights_when_there_is_activity_in_the_kitchen:
  module: activity_based_light_control_automations
  class: TurnOnAutomation
  observed_activity_sensor: binary_sensor.kitchen_sensor_1_motion_detected
  light_group: light.kitchen_lights
  light_sensor: sensor.kitchen_light_intensity_percent
  scene_input_select: input_select.kitchen_automatic_light_scene_generated
  scene_group_prefix: kitchen
  light_intensity_toggle_threshold: input_number.kitchen_light_toogle_intensity_threshold
  light_automation_start_time: input_datetime.kitchen_light_automation_start_time
  light_automation_end_time: input_datetime.kitchen_light_automation_end_time
  enable_time_depended_automation_input: input_boolean.kitchen_time_depended_light_automation_is_enabled
  enable_automatic_scene_mode: input_boolean.kitchen_automatic_scene_mode_enabled
  constrain_input_boolean: input_boolean.kitchen_light_automation_is_enabled

set_kitchen_timebased_light_scene:
  module: time_based_scene_switch
  class: TimeBasedSceneSwitch
  scene_switch_input_select: input_select.kitchen_time_based_scenes
  toggled_scene_input_select: input_select.kitchen_automatic_light_scene_generated
  light_automatic_enabled: input_boolean.kitchen_light_automation_is_enabled

reactivate_kitchen_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.kitchen_light_automation_is_enabled
  reactivation_timeout: input_datetime.kitchen_light_automation_reactivation_timeout

turn_off_lights_when_there_is_no_activity_in_the_kitchen:
  module: activity_based_light_control_automations
  class: TurnOffAutomation
  light_group: light.kitchen_lights
  turn_off_timeout: input_number.kitchen_light_turn_off_timeout
  observed_activity_sensor: binary_sensor.kitchen_sensor_1_motion_detected
  constrain_input_boolean: input_boolean.kitchen_light_automation_is_enabled