
activity_controlled_light_kitchen:
  module: activity_based_automations
  class: ActivityBasedLightControl
  dependencies: 
    - scene_utils
    - hass_utils
  observed_activity_sensor: binary_sensor.kitchen_sensor_motion_detected
  light_group: light.kitchen_lights
  turn_off_timeout: input_number.kitchen_light_turn_off_timeout
  constrain_input_boolean: input_boolean.kitchen_light_automation_is_enabled
  time_based_scene_mode:
    constrain_input_boolean: input_boolean.kitchen_automatic_scene_mode_enabled
    scene_input_select: input_select.kitchen_automatic_light_scene_generated
    scene_group_prefix: kitchen
  light_sensor_control:
    light_sensor: sensor.kitchen_sensor_light_intensity
    light_intensity_toggle_threshold: input_number.kitchen_light_toogle_intensity_threshold

set_kitchen_timebased_light_scene:
  module: time_based_scene_switch
  class: TimeBasedSceneSwitch
  dependencies: 
    - scene_utils
  scene_switch_input_select: input_select.kitchen_time_based_scenes
  toggled_scene_input_select: input_select.kitchen_automatic_light_scene_generated
  light_automatic_enabled: input_boolean.kitchen_light_automation_is_enabled
  light_group: light.kitchen_lights
  scene_group_prefix: kitchen

reactivate_kitchen_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.kitchen_light_automation_is_enabled
  reactivation_timeout: input_datetime.kitchen_light_automation_reactivation_timeout

kitchen_scene_switch:
  module: input_select_scene_switch
  class: InputSelectSceneSwitch
  observed_input_select: input_select.kitchen_light_scene_generated
  scene_prefix: kitchen
  adapted_input_selects:
    - input_select.kitchen_automatic_light_scene_generated