reactivate_kitchen_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.kitchen_light_automation_is_enabled
  reactivation_timeout: input_datetime.kitchen_light_automation_reactivation_timeout

kitchen_scene_switch:
  module: input_select_scene_switch
  class: InputSelectSceneSwitch
  observed_input_select: input_select.kitchen_light_scene_generated
  scene_prefix: kitchen
  adapted_input_selects:
    - input_select.kitchen_automatic_light_scene_generated