toggle_plant_light_after_given_time_frame:
  module: time_based_toggle_automations
  class: TimeBasedToggleAutomation
  time_interval_start: input_datetime.kitchen_plant_light_turn_on_time
  time_interval_end: input_datetime.kitchen_plant_light_turn_off_time
  toggled_entity: switch.hue_smart_plug_1
  input_constraint: input_boolean.kitchen_plant_light_automation_enabled

toggle_plant_ventilation_together_with_plant_automation_in_given_time_frame:
  module: time_based_toggle_automations
  class: TimeBasedToggleAutomation
  time_interval_start: input_datetime.kitchen_plant_light_turn_on_time
  time_interval_end: input_datetime.kitchen_plant_light_turn_off_time
  toggled_entity: switch.hue_smart_plug_2
  input_constraint: input_boolean.kitchen_plant_light_automation_enabled

toggle_plant_watering_in_given_interval:
  module: time_based_toggle_automations
  class: TurnOnOffInterval
  on_interval_length: input_number.kitchen_plant_watering_duration
  off_interval_length: input_number.kitchen_plant_watering_interval
  toggled_entity: switch.kitchen_plant_controller_pump_relais_1
  input_constraint: input_boolean.kitchen_plant_watering_automation_enabled
  skip_first: true

toggle_plant_ventilation_in_given_interval_at_night_time:
  module: time_based_toggle_automations
  class: TurnOnOffInterval
  on_interval_length: input_number.kitchen_plant_night_ventilation_on_interval
  off_interval_length: input_number.kitchen_plant_night_ventilation_off_interval
  toggled_entity: switch.hue_smart_plug_2
  interval_start: input_datetime.kitchen_plant_night_ventilation_turn_on_time
  interval_end: input_datetime.kitchen_plant_light_turn_on_time
  input_constraint: input_boolean.kitchen_plant_ventilation_automation_enabled

plant_status_lcd_display_rotation:
  module: lcd_display_rotation
  class: LCDDisplayRotation
  displayed_entities:
    - entity: sensor.kitchen_plant_controller_humidity
      name: Humidity
      unit: "%"
    - entity: sensor.kitchen_plant_controller_temperature
      name: Temperature
      unit: "deg. C"
    - entity: sensor.kitchen_plant_controller_moisture_1
      name: Moisture Right
      unit: "%"
    - entity: sensor.kitchen_plant_controller_moisture_2
      name: Moisture Left
      unit: "%"
  rotate_timeout: 10
  mqtt_display: kitchen_mqtt_lcd_display/show