toggle_plant_light_after_given_time_frame:
  module: time_based_toggle_automations
  class: TimeBasedToggleAutomation
  time_interval_start: input_datetime.kitchen_plant_light_turn_on_time
  time_interval_end: input_datetime.kitchen_plant_light_turn_off_time
  toggled_entity: switch.kitchen_plant_closet_lights
  constrain_input_boolean: input_boolean.kitchen_plant_light_automation_enabled

toggle_plant_ventilation_in_given_interval_at_night_time:
  module: time_based_toggle_automations
  class: TurnOnOffInterval
  on_interval_length: input_number.kitchen_plant_night_ventilation_on_interval
  off_interval_length: input_number.kitchen_plant_night_ventilation_off_interval
  toggled_entity: switch.hue_smart_plug_2
  interval_start: input_datetime.kitchen_plant_night_ventilation_turn_on_time
  interval_end: input_datetime.kitchen_plant_light_turn_on_time
  constrain_input_boolean: input_boolean.kitchen_plant_ventilation_automation_enabled
