- alias: 'Turn off TV when its in paused state for several minutes'
  trigger:
    entity_id: media_player.tv_livingroom
    platform: state
    to: 'paused'
    for:
      minutes: 7
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.tv_livingroom