- platform: template
  sensors:
    living_room_tv_is_playing:
      friendly_name: "Living Room TV is Playing"
      icon_template: mdi:television-play
      value_template: >-
        {{ is_state('media_player.tv_livingroom', 'playing') }}
    living_room_tv_is_on:
      icon_template: mdi:monitor-dashboard
      value_template: >-
        {{ not is_state('media_player.tv_livingroom', 'off') }}
    activity_detected_in_living_room:
      friendly_name: "Activity detected in living room"
      icon_template: mdi:monitor-dashboard
      value_template: >-
        {{ is_state('media_player.tv_livingroom', 'playing') 
        or is_state('binary_sensor.living_room_sensor_actor_1_motion_detected', 'on') }}