- platform: group
  name: Living Room Indirect Lights
  entities:
    - light.living_room_hue_light_bulb
    - light.living_room_standing_light_1
    - light.living_room_standing_light_2
    - light.living_room_round_light
    - light.living_room_globe_light
    - light.living_room_sensor_actor_2_light_strings
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_ceiling_light
    - light.living_room_hue_light_bulb
    - light.living_room_standing_light_1
    - light.living_room_standing_light_2
    - light.living_room_round_light
    - light.living_room_globe_light
    - light.living_room_sensor_actor_2_light_strings