- platform: mqtt
  name: "Living Room Closet Light"
  state_topic: "living_room/closet_light/status"
  command_topic: "living_room/closet_light/switch"
  brightness_command_topic: "living_room/closet_light/brightness/set"
  brightness_state_topic: "living_room/closet_light/brightness/status"
  rgb_state_topic: "living_room/closet_light/color/status"
  rgb_command_topic: "living_room/closet_light/color/set"
  state_value_template: "{{ value_json.state }}"
  rgb_value_template: "{{ value_json.rgb | join(',') }}"
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: group
  name: Living Room Indirect Lights
  entities:
    - light.living_room_philips_hue_iris_light
    - light.living_room_closet_light
    - light.living_room_standing_light
- platform: group
  name: Living Room Ceiling Lights
  entities:
    - light.living_room_center_1
    - light.living_room_center_2
    - light.living_room_center_3
    - light.living_room_center_4
    - light.living_room_center_5
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_center_1
    - light.living_room_center_2
    - light.living_room_center_3
    - light.living_room_center_4
    - light.living_room_center_5
    - light.living_room_philips_hue_iris_light
    - light.living_room_closet_light
    - light.living_room_standing_light