- platform: group
  name: Living Room Indirect Lights
  entities:
    - light.hue_iris_light
    - light.living_room_sensor_actor_1_closet_rgb_lights
    - light.living_room_standing_light
    - light.esp_couch_light_rgb_i2c_light
- platform: group
  name: Living Room Ceiling Lights
  entities:
    - light.living_room_center_1
    - light.living_room_center_2
    - light.living_room_center_3
    - light.living_room_center_4
    - light.living_room_center_5
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_center_1
    - light.living_room_center_2
    - light.living_room_center_3
    - light.living_room_center_4
    - light.living_room_center_5
    - light.hue_iris_light
    - light.living_room_sensor_actor_1_closet_rgb_lights
    - light.living_room_standing_light
    - light.esp_couch_light_rgb_i2c_light