reactivate_living_room_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.living_room_light_automation_is_enabled
  reactivation_timeout: input_datetime.living_room_light_automation_reactivation_timeout

activity_controlled_light_living_room:
  module: activity_based_automations
  class: ActivityBasedLightControl
  dependencies: 
    - scene_utils
    - hass_utils
  observed_activity_sensor: binary_sensor.activity_detected_in_living_room
  light_group: light.living_room_lights
  turn_off_timeout: input_number.living_room_light_turn_off_timeout
  constrain_input_boolean: input_boolean.living_room_light_automation_is_enabled
  time_based_scene_mode:
    constrain_input_boolean: input_boolean.living_room_automatic_scene_mode_enabled
    scene_input_select: input_select.living_room_automatic_light_scene_generated
    scene_group_prefix: living_room
  light_sensor_control:
    light_sensor: sensor.living_room_sensor_actor_2_light_intensity
    light_intensity_toggle_threshold: input_number.living_room_light_toogle_intensity_threshold

set_living_room_timebased_light_scene:
  module: time_based_scene_switch
  class: TimeBasedSceneSwitch
  dependencies: 
    - scene_utils
  scene_switch_input_select: input_select.living_room_time_based_scenes
  toggled_scene_input_select: input_select.living_room_automatic_light_scene_generated
  light_automatic_enabled: input_boolean.living_room_light_automation_is_enabled
  scene_group_prefix: living_room
  light_group: light.living_room_lights

living_room_scene_switch:
  module: input_select_scene_switch
  class: InputSelectSceneSwitch
  observed_input_select: input_select.living_room_light_scene_generated
  scene_prefix: living_room
  adapted_input_selects:
    - input_select.living_room_automatic_light_scene_generated