reactivate_living_room_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.living_room_light_automation_is_enabled
  reactivation_timeout: input_datetime.living_room_light_automation_reactivation_timeout

living_room_scene_switch:
  module: input_select_scene_switch
  class: InputSelectSceneSwitch
  observed_input_select: input_select.living_room_light_scene_generated
  scene_prefix: living_room
  adapted_input_selects:
    - input_select.living_room_light_scene_generated