- alias: Turn off bedroom lights when there is no movement
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_1_motion_detected
    to: 'off'
    for:
      seconds: 300
  action:
    - service: light.turn_off
      entity_id: light.all_bedroom_lights

- alias: Notify Smart Button Was Pressed
  trigger:
    - platform: state
      entity_id: 'sensor.hue_smart_button_1_action'
      to: 'press'
    - platform: state
      entity_id: 'sensor.hue_smart_button_2_action'
      to: 'press'
  action:
    service: script.turn_on
    entity_id: script.notify_smart_button_pressed
    data:
      variables:
        smart_button_id: "{{ trigger.entity_id }}"

- alias: Toggle Bedroom Room Lights on Smart Button Release
  trigger:
    - platform: event
      event_type: SMART_HOME_BUTTON_RELEASE
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.entity_id ==  'sensor.hue_smart_button_1_action'}}"
  action:
    service: script.turn_on
    entity_id: script.toggle_light_scene
    data:
      variables:
        light_group_id: 'light.all_bedroom_lights'
        scene_input_select_id: 'input_select.bedroom_light_scene'

- alias: Toggle Bedroom Scene on Smart Button Press
  trigger:
    - platform: event
      event_type: SMART_HOME_BUTTON_PRESS
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.entity_id ==  'sensor.hue_smart_button_1_action'}}"
  action:
    - service: input_select.select_next
      entity_id: input_select.bedroom_light_scene
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states('input_select.bedroom_light_scene') }}"

- alias: Apply Smart Button Dim Operation Increase to Bedroom Lights
  trigger:
    - platform: state
      entity_id: 'sensor.hue_smart_button_1_action'
      to: 'skip_forward'
  action:
    - service: input_number.increment
      entity_id: input_number.bedroom_light_brightness

- alias: Apply Smart Button Dim Operation Decrease to Bedroom Lights
  trigger:
    - platform: state
      entity_id: 'sensor.hue_smart_button_1_action'
      to: 'skip_backward'
  action:
    - service: input_number.decrement
      entity_id: input_number.bedroom_light_brightness

- alias: Apply Brightness to Bedroom Lights
  trigger:
    - platform: state
      entity_id: input_number.bedroom_light_brightness
  action:
    - service: light.turn_on
      entity_id: light.bedroom_lights
      data_template:
        brightness: "{{ states('input_number.bedroom_light_brightness') | int }}"