- alias: Toggle bedroom bed light on button press
  trigger:
    platform: state
    entity_id: sensor.hue_smart_button_4_action
    to: "press"
  action:
    - service: light.toggle
      entity_id: light.bedroom_bed_light

- alias: Turn on bedroom light automation on button hold
  trigger:
    platform: state
    entity_id: sensor.hue_smart_button_4_action
    to: "hold"
  condition:
    condition: state
    entity_id: input_boolean.bedroom_light_automation_is_enabled
    state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedroom_light_automation_is_enabled
    - service: pyscript.toggle_scene_from_input_select
      data:
        scene_input_select: input_select.bedroom_automatic_light_scene_generated
        scene_prefix: Bedroom

- alias: Turn off bedroom light automation on button hold
  trigger:
    platform: state
    entity_id: sensor.hue_smart_button_4_action
    to: "hold"
  condition:
    condition: state
    entity_id: input_boolean.bedroom_light_automation_is_enabled
    state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_light_automation_is_enabled
    - service: light.turn_off
      entity_id: light.all_bedroom_lights


- alias: Toggle bedroom workstation on button press
  trigger:
    platform: state
    entity_id: sensor.hue_smart_button_2_action
    to: "press"
  action:
    - service: switch.toggle
      entity_id: switch.work_station_power_switch

- alias: Open Bedroom Blinds On Button Event
  trigger:
    - platform: state
      entity_id: sensor.bedroom_blind_button_2_action
      to: "open"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_right

- alias: Open Bedroom Blinds And Activate Light Automation On Button Event
  trigger:
    - platform: state
      entity_id: sensor.bedroom_blind_button_1_action
      to: "open"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_right
    - condition: and
      conditions:
       - condition: time
         alias: "In the Morning"
         before: "12:00:00"
       - condition: state
         alias: "Automation activated"
         entity_id: input_boolean.bedroom_blind_automation_is_enabled
         state: "on"
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.bedroom_light_automation_is_enabled

- alias: Close Bedroom Blinds On Button Event
  trigger:
    - platform: state
      entity_id: sensor.bedroom_blind_button_1_action
      to: "close"
    - platform: state
      entity_id: sensor.bedroom_blind_button_2_action
      to: "close"
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_right

- alias: Close Bedroom Blinds When Sun Is Below Horizon
  trigger:
    - platform: state
      entity_id: sun.sun
      from: above_horizon
      to: below_horizon
  condition:
    - condition: state
      alias: "Automation activated"
      entity_id: input_boolean.bedroom_blind_automation_is_enabled
      state: "on"
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_right
