- alias: Turn on bedroom closet light when door was opened
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_1_door_open
    to: 'on'
  condition:
    - condition: state
      entity_id: light.bedroom_closet_led_power_supply_light
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.bedroom_closet_led_power_supply_light
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before

- alias: Return to former light state when bedroom closet was closed again
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_1_door_open
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before
    - service: light.turn_off
      entity_id: light.bedroom_closet_led_power_supply_light

- alias: Turn on bedroom lights when there is activity and little light
  trigger:
    - platform: state
      entity_id: binary_sensor.activity_detected_in_bedroom
      to: 'on'
  condition:
    - condition: state
      entity_id: light.all_bedroom_lights
      state: 'off'
    - condition: time
      after: "10:00:00"
      before: "23:00:00"
    - condition: numeric_state
      entity_id: sensor.bedroom_light_intensity_percent
      below: 45
  action:
    - service: script.turn_on
      entity_id: script.toggle_scene_from_input_select
      data:
        variables:
          input_select_entity: "input_select.bedroom_light_scene"

- alias: Turn off bedroom lights when light is sufficient
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_light_intensity_percent
      above: 45
      for:
        seconds: 60
  condition:
    - condition: state
      entity_id: light.all_bedroom_lights
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.all_bedroom_lights

- alias: Turn off bedroom lights when there is no activity
  trigger:
    platform: state
    entity_id: binary_sensor.activity_detected_in_bedroom
    to: 'off'
    for:
      seconds: 240
  condition:
    - condition: state
      entity_id: light.all_bedroom_lights
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.all_bedroom_lights

- alias: Apply bedroom scenes when input select changes
  trigger:
    - platform: state
      entity_id: input_select.bedroom_light_scene
  action:
    - service: script.turn_on
      entity_id: script.toggle_scene_from_input_select
      data:
        variables:
          input_select_entity: "input_select.bedroom_light_scene"

- alias: Notify Smart Button Was Pressed
  trigger:
    - platform: state
      entity_id: 'sensor.hue_smart_button_1_action'
      to: 'press'
    - platform: state
      entity_id: 'sensor.hue_smart_button_2_action'
      to: 'press'
  action:
    service: script.turn_on
    entity_id: script.notify_smart_button_pressed
    data:
      variables:
        smart_button_id: "{{ trigger.entity_id }}"

- alias: Toggle Bedroom Room Lights on Smart Button Release
  trigger:
    - platform: event
      event_type: SMART_HOME_BUTTON_RELEASE
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.entity_id ==  'sensor.hue_smart_button_1_action'}}"
  action:
    service: script.turn_on
    entity_id: script.toggle_light_scene
    data:
      variables:
        light_group_id: 'light.all_bedroom_lights'
        scene_input_select_id: 'input_select.bedroom_light_scene'

- alias: Toggle Bedroom Scene on Smart Button Press
  trigger:
    - platform: event
      event_type: SMART_HOME_BUTTON_PRESS
  condition:
    - condition: template
      value_template: "{{ trigger.event.data.entity_id ==  'sensor.hue_smart_button_1_action'}}"
  action:
    - service: input_select.select_next
      entity_id: input_select.bedroom_light_scene
    - service: script.turn_on
      entity_id: script.toggle_scene_from_input_select
      data:
        variables:
          input_select_entity: "bedroom_light_scene"

- alias: Apply Smart Button Dim Operation Increase to Bedroom Lights
  trigger:
    - platform: state
      entity_id: 'sensor.hue_smart_button_1_action'
      to: 'skip_forward'
  action:
    - service: input_number.increment
      entity_id: input_number.bedroom_light_brightness

- alias: Apply Smart Button Dim Operation Decrease to Bedroom Lights
  trigger:
    - platform: state
      entity_id: 'sensor.hue_smart_button_1_action'
      to: 'skip_backward'
  action:
    - service: input_number.decrement
      entity_id: input_number.bedroom_light_brightness

- alias: Apply Brightness to Bedroom Lights
  trigger:
    - platform: state
      entity_id: input_number.bedroom_light_brightness
  action:
    - service: light.turn_on
      entity_id: light.all_bedroom_lights
      data_template:
        brightness: "{{ states('input_number.bedroom_light_brightness') | int }}"