- alias: Turn on bedroom closet light when door was opened
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_door_sensor
    to: "on"
  condition:
    - condition: state
      entity_id: light.bedroom_closet_led_power_supply_light
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.bedroom_closet_led_power_supply_light
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before

- alias: Return to former light state when bedroom closet was closed again
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_door_sensor
    to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before
    - service: light.turn_off
      entity_id: light.bedroom_closet_led_power_supply_light

- alias: Rotate Light Scene On IOS event
  trigger:
    platform: event
    event_type: ios.action_fired
    event_data:
      actionID: ED3CF43F-E74C-43C7-A191-3EDF1AFD00A4
      sourceDeviceID: iphone_von_robert
  action:
    - service: input_select.select_next
      entity_id: input_select.bedroom_light_scene_generated

- alias: Open Bedroom Blinds On Button Event
  trigger:
    - platform: state
      entity_id: sensor.bedroom_blind_button_2_action
      to: "open"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_center
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_right

- alias: Open Bedroom Blinds And Activate Light Automation On Button Event
  trigger:
    - platform: state
      entity_id: sensor.bedroom_blind_button_1_action
      to: "open"
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_center
    - service: cover.open_cover
      target:
        entity_id: cover.bedroom_blind_right
    - condition: and
      conditions:
       - condition: time
         alias: "In the Morning"
         before: "12:00:00"
       - condition: state
         alias: "Automation activated"
         entity_id: input_boolean.bedroom_blind_automation_is_enabled
         state: "on"
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.bedroom_light_automation_is_enabled

- alias: Close Bedroom Blinds On Button Event
  trigger:
    - platform: state
      entity_id: sensor.bedroom_blind_button_1_action
      to: "close"
    - platform: state
      entity_id: sensor.bedroom_blind_button_2_action
      to: "close"
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_center
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_right

- alias: Close Bedroom Blinds When Sun Is Below Horizon
  trigger:
    - platform: state
      entity_id: sun.sun
      from: above_horizon
      to: below_horizon
  condition:
    - condition: state
      alias: "Automation activated"
      entity_id: input_boolean.bedroom_blind_automation_is_enabled
      state: "on"
  action:
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_left
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_center
    - service: cover.close_cover
      target:
        entity_id: cover.bedroom_blind_right
