- alias: Turn on bedroom closet light when door was opened
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_1_door_open
    to: 'on'
  condition:
    - condition: state
      entity_id: light.bedroom_closet_led_power_supply_light
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.bedroom_closet_led_power_supply_light
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before

- alias: Return to former light state when bedroom closet was closed again
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_sensor_1_door_open
    to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_closet_light_was_turned_off_before
    - service: light.turn_off
      entity_id: light.bedroom_closet_led_power_supply_light

- alias: Apply bedroom scenes when input select changes
  trigger:
    - platform: state
      entity_id: input_select.bedroom_light_scene_generated
  action:
    - service: script.turn_on
      entity_id: script.toggle_scene_from_input_select
      data:
        variables:
          input_select_entity: "input_select.bedroom_light_scene_generated"

