- platform: template
  sensors:
    bedroom_sensor_1_device_status:
      friendly_name: "Bedroom Sensor 1 Device Status"
      device_class: connectivity
      value_template: >-
        {{ is_state('binary_sensor.bedroom_sensor_1_ping', 'on') }}
      delay_off:
        seconds: 75