- platform: template
  sensors:
    bedroom_activity_detected_on_pcs:
      friendly_name: "Activity detected in bedroom"
      icon_template: mdi:account-cog
      value_template: >-
        {{ is_state('binary_sensor.private_laptop_activity', 'on') 
        or is_state('binary_sensor.work_laptop_activity', 'on')
        or is_state('binary_sensor.lenovo_new_gen_key_was_pressed', 'on')
        or is_state('binary_sensor.lenovo_new_gen_mouse_moved', 'on')}}
    activity_detected_in_bedroom:
      friendly_name: "Activity detected in bedroom"
      icon_template: mdi:account-cog
      value_template: >-
        {{ is_state('binary_sensor.bedroom_sensor_1_motion_detected', 'on') 
        or is_state('binary_sensor.bedroom_activity_detected_on_pcs', 'on') }}
    robert_think_pad_is_on:
      friendly_name: "Robert Think-Pad is on"
      icon_template: mdi:monitor-dashboard
      value_template: >-
        {{ is_state('sensor.robert_thinkpad_running', '1') }}
    robert_work_laptop_is_on:
      friendly_name: "Work Laptop is on"
      icon_template: mdi:monitor-dashboard
      value_template: >-
        {{ is_state('sensor.work_laptop_running', '1') }}
