- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_ceiling_1
    - light.bedroom_ceiling_2
    - light.bedroom_ceiling_3
    - light.bedroom_workdesk
    - light.bedroom_closet_led_power_supply_light