- platform: group
  name: Bedroom Indirect Lights
  entities:
    - light.bedroom_workdesk_light
    - light.bedroom_sensor_neopixel_partition_light_1
    - light.bedroom_sensor_neopixel_partition_light_2
    - light.bedroom_sensor_neopixel_partition_light_3

- platform: group
  name: Bedroom NeoPixel Light
  entities:
    - light.bedroom_sensor_neopixel_partition_light_1
    - light.bedroom_sensor_neopixel_partition_light_2
    - light.bedroom_sensor_neopixel_partition_light_3
- platform: group
  name: All Bedroom Lights
  entities:
    - light.bedroom_workdesk_light
    - light.bedroom_ceiling_light
    - light.bedroom_sensor_neopixel_partition_light_1
    - light.bedroom_sensor_neopixel_partition_light_2
    - light.bedroom_sensor_neopixel_partition_light_3
    - light.bedroom_bed_light
