- platform: group
  name: Bedroom Indirect Lights
  entities:
    - light.bedroom_workdesk_light
    - light.bedroom_closet_led_power_supply_light
    - light.bedroom_bed_light
- platform: group
  name: Bedroom Ceiling Lights
  entities:
    - light.bedroom_ceiling_1
    - light.bedroom_ceiling_2
    - light.bedroom_ceiling_3
- platform: group
  name: All Bedroom Lights
  entities:
    - light.bedroom_ceiling_1
    - light.bedroom_ceiling_2
    - light.bedroom_ceiling_3
    - light.bedroom_bed_light
    - light.bedroom_workdesk_light
    - light.bedroom_closet_led_power_supply_light
