- platform: prometheus-query
  name: Robert ThinkPad Running
  prometheus_url:  !secret prometheus_url
  prometheus_query: up{instance="robert-ThinkPad-NewGen:9100",job="robert-thinkpad"}
  scan_interval: 10

- platform: prometheus-query
  name: Work Laptop Running
  prometheus_url: !secret prometheus_url
  prometheus_query: up{instance="L64978-WDD:9182",job="work-laptop"}
  scan_interval: 10