- platform: template
  sensors:
    bedroom_light_intensity_percent:
      friendly_name: "Bedroom Light Intensity %"
      icon_template: mdi:brightness-percent
      unit_of_measurement: "%"
      value_template: >-
        {{ ((states('sensor.bedroom_sensor_1_light_intensity') | float / 3.3) | float* 100) | round(0) }}

- platform: prometheus-query
  name: Robert ThinkPad Running
  prometheus_url:  !secret prometheus_url
  prometheus_query: up{instance="robert-ThinkPad-NewGen:9100",job="robert-thinkpad"}
  scan_interval: 10

- platform: prometheus-query
  name: Work Laptop Running
  prometheus_url: !secret prometheus_url
  prometheus_query: up{instance="L64978-WDD:9182",job="work-laptop"}
  scan_interval: 10