- alias: Turn on floor light when there is movement
  trigger:
    - platform: state
      entity_id: binary_sensor.floor_motion_detector
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.kitchen_outside_light_intensity
      below: 800
  action:
    - service: light.turn_on
      entity_id: light.floor_lights

- alias: Turn off floor lights when there is no movement
  trigger:
    platform: state
    entity_id: binary_sensor.floor_motion_detector
    to: 'off'
    for:
      seconds: 45
  action:
    - service: light.turn_off
      entity_id: light.floor_lights
    