- platform: group
  name: Floor Lights
  entities:
    - light.floor_light
    - light.floor_sensor_actor_neopixel_partition_light_1
    - light.floor_sensor_actor_neopixel_partition_light_2
    - light.floor_sensor_actor_neopixel_partition_light_3
    - light.floor_sensor_actor_neopixel_partition_light_4
- platform: group
  name: Floor Neo Pixel Light
  entities:
    - light.floor_sensor_actor_neopixel_partition_light_1
    - light.floor_sensor_actor_neopixel_partition_light_2
    - light.floor_sensor_actor_neopixel_partition_light_3
    - light.floor_sensor_actor_neopixel_partition_light_4