- platform: mqtt
  name: "Balcony Humidity"
  state_topic: "balcony/humidity"
  payload_available: "online"
  payload_not_available: "offline"
  icon: 'mdi:water-percent'
- platform: mqtt
  name: "Balcony Temperature"
  state_topic: "balcony/temperature"
  payload_available: "online"
  payload_not_available: "offline"
  icon: 'mdi:thermometer'