- binary_sensor:
    name: Balcony Sensor Actor Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.balcony_sensor_actor_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Bathroom Sensor Actor Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.bathroom_sensor_actor_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Bedroom Sensor Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.bedroom_sensor_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Floor Sensor Actor Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.floor_sensor_actor_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Kitchen Ceiling Light Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.kitchen_ceiling_light_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Kitchen Light Controller Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.kitchen_light_controller_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Kitchen MQTT LCD Display Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.kitchen_mqtt_lcd_display_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Kitchen Sensor Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.kitchen_sensor_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Living Room Sensor Actor 1 Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.living_room_sensor_actor_1_os_version").split(" ")[0]) }}
- binary_sensor:
    name: Living Room Sensor Actor 2 Update Available
    state: >
        {{ is_state("binary_sensor.esphome_update_sensor", "off") and (state_attr("binary_sensor.esphome_update_sensor", "tag") != states("sensor.living_room_sensor_actor_2_os_version").split(" ")[0]) }}
