pyscript:
  allow_all_imports: true
  hass_is_global: true
apps:
  home_server_update:
    update_log: /config/tmp/apt_update.log
  state_observer:
    trigger_alarm_when_fridge_is_open:
      observed_entity: binary_sensor.kitchen_sensor_door_sensor
      observed_state: "on"
      timeout_input_number: input_number.kitchen_frigde_door_open_alarm_timeout
      actions:
        - service: notify.mobile_app_iphone_von_robert
          arguments:
            title: "Kühlschrank Tür offen!"
            message: "Tür wurde offen gelassen"
            data:
              actions:
                - action: "URI"
                  title: "Küchenübersicht öffnen"
                  uri: "/lovelace/kitchen"
        - service: pyscript.light_blink
          arguments:
            entity: light.kitchen_ceiling_light_light_switch
            state_entity: binary_sensor.kitchen_sensor_door_sensor
            target_state: "on"
      state_resolved_actions:
        - service: notify.mobile_app_iphone_von_robert
          arguments:
            title: "Kühlschrank Tür zu."
            message: "Wurde wieder geschlossen"
    trigger_alarm_when_plant_closet_is_too_hot:
      observed_entity: binary_sensor.temperature_too_hot_in_plant_closet
      observed_state: "on"
      actions:
        - service: notify.mobile_app_iphone_von_robert
          arguments:
            title: "Temperatur Alarm"
            message: "Pflanzenschrank Temperatur checken..."
            data:
              actions:
                - action: "URI"
                  title: "Küchenübersicht öffnen"
                  uri: "/lovelace/kitchen"
      state_resolved_actions:
        - service: notify.mobile_app_iphone_von_robert
          arguments:
            title: "Temperatur Alarm aufgehoben"
            message: "Temperatur im Pflanzenschrank wieder normal"
  lcd_display_rotation:
    display_topic: kitchen_mqtt_lcd_display/show
    rotate_timeout_entity: input_number.lcd_display_rotation_timeout
    rotation_enabled_entity: input_boolean.kitchen_lcd_display_rotation_enabled
    displayed_entities:
      - entity: sensor.kitchen_plant_controller_humidity
        name: Humidity
        unit: "%"
      - entity: sensor.kitchen_plant_controller_temperature
        name: Temperature
        unit: "deg. C"
      - entity: sensor.kitchen_plant_controller_moisture_sensor_3
        name: Moisture Left
        unit: "%"
      - entity: sensor.kitchen_plant_controller_moisture_sensor_1
        name: Moisture Middle
        unit: "%"
      - entity: sensor.kitchen_plant_controller_moisture_sensor_2
        name: Moisture Right
        unit: "%"
  global:
    esp_home_automations:
      esp_home_base_path: "/home/robert/docker/homeassistant/volumes/homeassistant/esphome"
    host_server:
      ssh_key: "/config/.ssh/id_rsa"
      ssh_login: "robert@rpn-home-server"
      ssh_sudo: !secret host_sudo
    home_assistant_docker_compose: "/home/robert/docker/homeassistant/docker-compose.yaml"
    server_monitoring_docker_compose: "/home/robert/docker/server_monitoring/docker-compose.yaml"
