- platform: template
  sensors:
    bathroom_motion_detector:
      device_class: motion
      friendly_name: "Bathroom Motion Detector"
      value_template: >-
        {{ is_state("binary_sensor.hue_motion_sensor_2_occupancy", "on") }}