- platform: template
  sensors:
    bathroom_temperature:
      friendly_name: "Bathroom Temperature" 
      unit_of_measurement: "°C"
      value_template: >-
        {{ state_attr("binary_sensor.hue_motion_sensor_2_occupancy", "temperature") }}
      icon_template: 'mdi:thermometer'
    bathroom_light_intensity:
      friendly_name: "Bathroom Light Intensity" 
      unit_of_measurement: "Lux"
      value_template: >-
        {{ state_attr("binary_sensor.hue_motion_sensor_2_occupancy", "illuminance_lux") }}
      icon_template: 'mdi:white-balance-sunny'
    bathroom_light_intensity_percent:
      friendly_name: "Bathroom Light Intensity in Percent" 
      icon_template: mdi:brightness-percent
      unit_of_measurement: "%"
      value_template: >-
          {{ state_attr("binary_sensor.hue_motion_sensor_2_occupancy", "illuminance_lux") | float / 100.0 | float * 100.0 }}