substitutions:
  node_name: balcony_sensor_actor
  node_board: nodemcuv2
  node_verbose_name: Balcony Sensor Actor
  dht_pin: D3
  dht_type: DHT22

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

sensor:
  - <<: !include common/sensor/dht.yaml

output:
  - platform: gpio
    id: relay_1
    pin: D1
  - platform: gpio
    id: relay_2
    pin: D2

light:
  - platform: binary
    name: "Balcony Sensor Actor Relay Light 1"
    output: relay_1
  - platform: binary
    name: "Balcony Sensor Actor Relay Light 2"
    output: relay_2