substitutions:
  node_name: bathroom_sensor_actor
  node_board: nodemcuv2
  node_verbose_name: Bathroom Sensor Actor
  # sensors
  motion_sensor_pin: D3
  dht_pin: D4
  dht_type: DHT22
  light_intensity_sensor_pin: A0
  light_intensity_sensor_update_interval: 10s

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

binary_sensor:
  - <<: !include common/binary_sensor/motion.yaml

sensor:
  - <<: !include common/sensor/dht.yaml
  - <<: !include common/sensor/light_intensity.yaml

output:
  - platform: gpio
    id: relay
    inverted: true
    pin: D2

light:
  - platform: binary
    name: ${node_verbose_name} Light
    output: relay
