esphome:
  name: bathroom_sensor_actor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret WIFI_SSID
  password: !secret WIFI_PASS

  ap:
    ssid: "Bathroom Sensor Actor"
    password: "6HcUr2h3UrDA"

mqtt:
  broker: !secret MQTT_BROKER
  username: !secret MQTT_USER
  password: !secret MQTT_PASSWORD

captive_portal:
logger:
ota:


binary_sensor:
  - platform: status
    name: "Bathroom Sensor Actor Connection Status"

text_sensor:
  - platform: version
    name: "Bathroom Sensor Actor OS Version"
  - platform: wifi_info
    ip_address:
      name: "Bathroom Sensor Actor IP Address"
    ssid:
      name: "Bathroom Sensor Actor Connected SSID"
    bssid:
      name: "Bathroom Sensor Actor Connected BSSID"
    mac_address:
      name: "Bathroom Sensor Actor Mac Wifi Address"


sensor:
  - platform: wifi_signal
    name: "Bathroom Sensor Actor WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "Bathroom Sensor Actor Uptime"
  - platform: dht
    pin: D8
    model: DHT22
    temperature:
      name: "Bathroom Sensor Actor Temperature"
    humidity:
      name: "Bathroom Sensor Actor Humidity"
    update_interval: 60s

output:
  - platform: gpio
    id: relay
    pin: D1
  - platform: esp8266_pwm
    id: strip_red
    pin: D5
  - platform: esp8266_pwm
    id: strip_green
    pin: D2
  - platform: esp8266_pwm
    id: strip_blue
    pin: D6
  

switch:
  - platform: restart
    name: "Bathroom Sensor Actor Restart"
  - platform: shutdown
    name: "Bathroom Sensor Actor Shutdown"


light:
  - platform: binary
    name: "Bathroom Sensor Actor Spots"
    output: relay
  - platform: rgb
    name: "Bathroom Sensor Actor Light Strip"
    red: strip_red
    green: strip_green
    blue: strip_blue
