substitutions:
  node_name: bedroom_sensor
  node_board: d1_mini
  node_verbose_name: Bedroom Sensor
  # sensors
  light_intensity_sensor_pin: A0
  light_intensity_sensor_update_interval: 10s
  door_sensor_pin: D2
  motion_sensor_pin: D3
  dht_pin: D4
  dht_type: DHT22

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

binary_sensor:
  - <<: !include common/binary_sensor/motion.yaml
  - <<: !include common/binary_sensor/door.yaml

sensor:
  - <<: !include common/sensor/dht.yaml
  - <<: !include common/sensor/light_intensity.yaml

light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO3
    num_leds: 100
    id: neopixellight
    name: ${node_verbose_name} NeoPixel Light
    internal: true
    variant: 800KBPS
  - platform: partition
    name: ${node_verbose_name} NeoPixel Partition Light 1
    id: neopixellight_segment_1
    segments:
      - id: neopixellight
        from: 0
        to: 31
  - platform: partition
    name: ${node_verbose_name} NeoPixel Partition Light 2
    id: neopixellight_segment_2
    segments:
      - id: neopixellight
        from: 32
        to: 66
  - platform: partition
    name: ${node_verbose_name} NeoPixel Partition Light 3
    id: neopixellight_segment_3
    segments:
      - id: neopixellight
        from: 67
        to: 99
