substitutions:
  node_name: esp_couch_light
  node_board: nodemcuv2
  node_verbose_name: ESP Couch Light
  # i2c
  sda_pin: "5"
  scl_pin: "4"

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml
  i2c_light: !include custom/i2cRGBLight.yaml
