substitutions:
  node_name: floor_sensor_actor
  node_board: nodemcuv2
  node_verbose_name: Floor Sensor Actor
  # sensors
  motion_sensor_pin: D7
  dht_pin: D3
  dht_type: DHT11
  # i2c
  sda_pin: "5"
  scl_pin: "4"

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml
  i2c_light: !include custom/i2cRGBLight.yaml

binary_sensor:
  - <<: !include common/binary_sensor/motion.yaml

sensor:
  - <<: !include common/sensor/dht.yaml
