substitutions:
  node_name: kitchen_plant_controller
  node_board: nodemcuv2
  node_verbose_name: Kitchen Plant Controller
  dht_pin: D3
  dht_type: DHT22

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

i2c:
  - id: i2cbus
    sda: 4
    scl: 5

ads1115:
  - address: 0x48

sensor:
  - <<: !include common/sensor/dht.yaml
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: ${node_verbose_name} Moisture Sensor 1 Raw Value
    update_interval: 5s
    unit_of_measurement: "V"
    icon: mdi:water-percent
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 4.096
    name: ${node_verbose_name} Moisture Sensor 1
    update_interval: 5s
    unit_of_measurement: "%"
    icon: mdi:water-percent
    filters:
      - calibrate_linear:
          - 1.2 -> 100.0
          - 2.9 -> 0.0
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    name: ${node_verbose_name} Moisture Sensor 2 Raw Value 
    update_interval: 5s
    unit_of_measurement: "V"
    icon: mdi:water-percent
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 4.096
    name: ${node_verbose_name} Moisture Sensor 2
    update_interval: 5s
    unit_of_measurement: "%"
    icon: mdi:water-percent
    filters:
      - calibrate_linear:
          - 1.0 -> 100.0
          - 3.3 -> 0.0
 
binary_sensor:
  - platform: gpio
    name: ${node_verbose_name} Swimmer Sensor
    pin:
      number: D4
      mode: INPUT_PULLUP

switch:
  - platform: gpio
    name: ${node_verbose_name} Pump Relay 1
    icon: mdi:water-pump
    pin: 
      number: D6
      inverted: True
  - platform: gpio
    name: ${node_verbose_name} Pump Relay 2
    icon: mdi:water-pump
    pin: 
      number: D5
      inverted: True
