substitutions:
  node_name: kitchen_sensor
  node_board: nodemcuv2
  node_verbose_name: Kitchen Sensor
  # sensors
  light_intensity_sensor_pin: A0
  light_intensity_sensor_update_interval: 10s
  door_sensor_pin: D1
  motion_sensor_pin: D2
  dht_pin: D3
  dht_type: DHT11

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

binary_sensor:
  - <<: !include common/binary_sensor/motion.yaml
  - <<: !include common/binary_sensor/door.yaml

sensor:
  - <<: !include common/sensor/dht.yaml
  - <<: !include common/sensor/light_intensity.yaml