substitutions:
  node_name: kitchen_light_controller
  node_board: nodemcuv2
  node_verbose_name: Kitchen Light Controller
 
packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

output:
  - platform: gpio
    id: relay
    pin: D1
  - platform: esp8266_pwm
    id: strip_red
    pin: D5
  - platform: esp8266_pwm
    id: strip_green
    pin: D2
  - platform: esp8266_pwm
    id: strip_blue
    pin: D6

light:
  - platform: binary
    name: ${node_verbose_name} Black Light
    output: relay
  - platform: rgb
    name: ${node_verbose_name} Light Strip
    red: strip_red
    green: strip_green
    blue: strip_blue
