substitutions:
  node_name: kitchen_mqtt_lcd_display
  node_board: nodemcuv2
  node_verbose_name: Kitchen MQTT LCD Display
  dht_pin: D4
  dht_type: DHT22

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml
  device_base: !include common/device_base.yaml

text_sensor:
  - platform: mqtt_subscribe
    name: "Kitchen MQTT LCD Display Display Topic"
    id: diplay_text_sensor
    topic: kitchen_mqtt_lcd_display/show

sensor:
  - <<: !include common/sensor/dht.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT
      inverted: true

    name: "Kitchen MQTT LCD Display Button Left"
  - platform: gpio
    pin:
      number: D0
      mode: INPUT
      inverted: true

    name: "Kitchen MQTT LCD Display Button Right"

display:
  - platform: lcd_gpio
    dimensions: 16x2
    data_pins:
      - D5
      - D6
      - D7
      - D8
    enable_pin: D3
    rs_pin: D2
    lambda: |-
      std::string toBeDisplayed = id(diplay_text_sensor).state;
      int currentDisplayIndex = 0;
      std::string currentLineDisplay = "";
      for (int i = 0; i < toBeDisplayed.length(); i++) {
        char& currentChar = toBeDisplayed.at(i);
        if (currentChar == '\n') {
          ESP_LOGD("Display", "displaying %s", currentLineDisplay.c_str());
          it.print(0, currentDisplayIndex, currentLineDisplay.c_str());

          currentLineDisplay = "";
          currentDisplayIndex += 1;
        } else {
          currentLineDisplay += currentChar;
        }
      }
      ESP_LOGD("Display", "displaying %s", currentLineDisplay.c_str());
      it.print(0, currentDisplayIndex, currentLineDisplay.c_str());
