substitutions:
  node_name: kitchen_ceiling_light
  node_board: esp01_1m
  node_verbose_name: Kitchen Ceiling Light
 
packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

output:
  - platform: gpio
    id: relay
    pin: 0

light:
  - platform: binary
    name: ${node_verbose_name} Light Switch
    output: relay