substitutions:
  node_name: living_room_sensor_actor_1
  node_board: nodemcuv2
  node_verbose_name: Living Room Sensor Actor 1
  # sensors
  motion_sensor_pin: D7
  dht_pin: D1
  dht_type: DHT11

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

binary_sensor:
  - <<: !include common/binary_sensor/motion.yaml

sensor:
  - <<: !include common/sensor/dht.yaml

output:
  - platform: esp8266_pwm
    id: strip_red
    pin: D5
  - platform: esp8266_pwm
    id: strip_green
    pin: D2
  - platform: esp8266_pwm
    id: strip_blue
    pin: D6

light:
  - platform: rgb
    name: ${node_verbose_name} Closet RGB Lights
    red: strip_red
    green: strip_green
    blue: strip_blue
