substitutions:
  node_name: living_room_sensor_actor_2
  node_board: nodemcuv2
  node_verbose_name: Living Room Sensor Actor 2
  # sensors
  light_intensity_sensor_pin: A0
  light_intensity_sensor_update_interval: 10s
  dht_pin: D1
  dht_type: DHT22

packages:
  mqtt: !include mqtt.yaml
  wifi: !include wifi.yaml 
  device_base: !include common/device_base.yaml

sensor:
  - <<: !include common/sensor/light_intensity.yaml
  - <<: !include common/sensor/dht.yaml

output:
  - platform: gpio
    id: relay
    pin: D3

light:
  - platform: binary
    name: ${node_verbose_name} Light Strings
    output: relay