homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://rpn-home-server
  user: zigbee2mqtt
  password: '!secret mqtt_password'
serial:
  port: /dev/ttyUSB0
devices:
  '0x84b4dbfffe0dd409':
    friendly_name: Bathroom Fan
  '0x001788010bb8d61c':
    friendly_name: Bathroom Indirect Light
  '0x0017880108fbda30':
    friendly_name: Bedroom Bed Light
  '0x84fd27fffe4168a2':
    friendly_name: Bedroom Blind Left
  '0x680ae2fffef46b27':
    friendly_name: Bedroom Blind Right
  '0x5c0272fffe5c18e2':
    friendly_name: Bedroom Blind Button 1
  '0x5c0272fffe5c1262':
    friendly_name: Bedroom Blind Button 2
  '0x001788010c02766a':
    friendly_name: Bedroom Ceiling Light
  '0x0017880108fbce9d':
    friendly_name: Bedroom Desk Plug 1
  '0x00124b00072a7628':
    friendly_name: Bedroom Desk Plug 2
  '0x00178801088ae425':
    friendly_name: Bedroom Workdesk Light
  '0x0017880109e64fc5':
    friendly_name: Hue Portable Light Bulb
  '0x0017880106051fb6':
    friendly_name: Hue Smart Button 1
  '0x001788010607b42e':
    friendly_name: Hue Smart Button 2
  '0x001788010606ff0d':
    friendly_name: Hue Smart Button 3
  '0x0017880108935396':
    friendly_name: Hue Smart Button 4
  '0x90fd9ffffede5ba1':
    friendly_name: Ikea Bedroom Smart Button
  '0x680ae2fffe9361a1':
    friendly_name: Ikea Kitchen Smart Button
  '0xd0cf5efffe20ba19':
    friendly_name: Ikea Living Room Smart Button
  '0x00178801088baad1':
    friendly_name: Kitchen Cabinet Light 1
  '0x00178801088ba8c1':
    friendly_name: Kitchen Cabinet Light 2
  '0x001788010678d276':
    friendly_name: Kitchen Entrance Light
  '0x680ae2fffe41499c':
    friendly_name: Kitchen Led Spots Light
  '0x00178801088aeb66':
    friendly_name: Kitchen Shelf Light
  '0x001788010c0abda0':
    friendly_name: Living Room Ceiling Light
  '0x00178801088bb74d':
    friendly_name: Living Room Globe Light
  '0x0017880100112ed7':
    friendly_name: Living Room Hue Light Bulb
  '0x001788010bcff64f':
    friendly_name: Living Room Motion Sensor
  '0x001788010c0ae634':
    friendly_name: Living Room Round Light
  '0x001788010679d58a':
    friendly_name: Living Room Standing Light 1
  '0x001788010c0231e4':
    friendly_name: Living Room Standing Light 2

