- platform: group
  name: Office Ceiling Lights
  entities:
    - light.office_ceiling_light_1
    - light.office_ceiling_light_2
    - light.office_ceiling_light_3
- platform: group
  name: All Office Lights
  entities:
    - light.office_ceiling_light_1
    - light.office_ceiling_light_2
    - light.office_ceiling_light_3
    - light.office_workdesk_light
