
activity_controlled_light_bathroom:
  module: activity_based_automations
  class: ActivityBasedEntityControl
  dependencies: 
    - scene_utils
    - hass_utils
  observed_activity_sensor: binary_sensor.bathroom_motion_detector
  entity: light.bathroom_lights
  turn_off_timeout: input_number.bathroom_light_turn_off_timeout
  constrain_input_boolean: input_boolean.bathroom_light_automation_is_enabled
  time_based_scene_mode:
    constrain_input_boolean: input_boolean.bathroom_automatic_scene_mode_enabled
    scene_input_select: input_select.bathroom_automatic_light_scene_generated
    scene_group_prefix: bathroom

set_bathroom_timebased_light_scene:
  module: time_based_scene_switch
  class: TimeBasedSceneSwitch
  dependencies: 
    - scene_utils
  scene_switch_input_select: input_select.bathroom_time_based_scenes
  toggled_scene_input_select: input_select.bathroom_automatic_light_scene_generated
  light_automatic_enabled: input_boolean.bathroom_light_automation_is_enabled
  scene_group_prefix: bathroom
  light_group: light.bathroom_lights

reactivate_bathroom_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.bathroom_light_automation_is_enabled
  reactivation_timeout: input_datetime.bathroom_light_automation_reactivation_timeout

bathroom_scene_switch:
  module: input_select_scene_switch
  class: InputSelectSceneSwitch
  observed_input_select: input_select.bathroom_light_scene_generated
  scene_prefix: bathroom
  adapted_input_selects:
    - input_select.bathroom_automatic_light_scene_generated