reactivate_bathroom_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.bathroom_light_automation_is_enabled
  reactivation_timeout: input_datetime.bathroom_light_automation_reactivation_timeout

bathroom_scene_switch:
  module: input_select_scene_switch
  class: InputSelectSceneSwitch
  observed_input_select: input_select.bathroom_light_scene_generated
  scene_prefix: bathroom
  adapted_input_selects:
    - input_select.bathroom_automatic_light_scene_generated