activity_controlled_light_floor:
  module: activity_based_automations
  class: ActivityBasedEntityControl
  dependencies: 
    - scene_utils
    - hass_utils
  observed_activity_sensor: binary_sensor.floor_sensor_actor_motion_detected
  entity: light.floor_lights
  turn_off_timeout: input_number.floor_light_turn_off_timeout
  constrain_input_boolean: input_boolean.floor_light_automation_is_enabled
  time_based_scene_mode:
    constrain_input_boolean: input_boolean.floor_automatic_scene_mode_enabled
    scene_input_select: input_select.floor_automatic_light_scene_generated
    scene_group_prefix: floor
  threshold_control:
    sensor: sensor.floor_sensor_actor_light_intensity
    threshold: input_number.floor_light_toogle_intensity_threshold

set_floor_timebased_light_scene:
  module: time_based_scene_switch
  class: TimeBasedSceneSwitch
  dependencies: 
    - scene_utils
  scene_switch_input_select: input_select.floor_time_based_scenes
  toggled_scene_input_select: input_select.floor_automatic_light_scene_generated
  light_automatic_enabled: input_boolean.floor_light_automation_is_enabled
  light_group: light.floor_lights
  scene_group_prefix: floor

reactivate_floor_light_automation_after_given_timeout:
  module: input_boolean
  class: ReactivationTimer
  observed_input_boolean: input_boolean.floor_light_automation_is_enabled
  reactivation_timeout: input_datetime.floor_light_automation_reactivation_timeout

floor_scene_switch:
  module: input_select_scene_switch
  class: InputSelectSceneSwitch
  observed_input_select: input_select.floor_light_scene_generated
  scene_prefix: floor
  adapted_input_selects:
    - input_select.floor_automatic_light_scene_generated